site_name: "Документация MeshCoreTel-firmware"
site_url: https://vbart.github.io/MeshCoreTel-firmware/
site_description: "Документация по специфичным для MeshCoreTel-firmware функциям: Wi-Fi, MQTT, веб-панель и API, также процессу выпуска релизов"

repo_name: VBart/MeshCoreTel-firmware
repo_url: https://github.com/VBart/MeshCoreTel-firmware
edit_uri: edit/main/meshcoretel-docs/
docs_dir: meshcoretel-docs

theme:
  name: material
  language: ru
  logo: _assets/vbart.svg
  favicon: _assets/vbart.svg
  features:
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Переключить на темную тему
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Переключить на светлую тему

extra_css:
  - _stylesheets/extra.css

nav:
  - Введение: index.md
  - Устройства: boards.md
  - Прошивка: releases.md
  - CLI-команды: custom-cli.md
  - Веб-панель: web-panel.md
  - Веб-API: api.md
  - Cборка: local-builds.md
